In [1]:
import pandas as pd
import numpy as np

In [3]:
outcomes = pd.read_csv("dataset/loan_outcomes_train.csv")
gps = pd.read_csv("dataset/gps.csv")
events = pd.read_csv("dataset/events.csv")

In [4]:
gps.head()

,id,accuracy,altitude,created_at,land_speed,latitude,location_provider,longitude,time_of_fix,user_id
0,1,5.9,1805.200000,2023-01-03 10:20:02.658238,0.000000,0.980968,fused,34.974597,2023-01-03 10:20:02.000,9054
1,2,3000.0,0.000000,2023-01-03 10:40:03.041653,0.000000,0.980212,fused,34.965993,2023-01-03 10:39:49.000,9054
2,3,14.1,1098.300000,2023-01-03 11:09:50.372891,0.000000,1.092587,fused,36.694963,2023-01-03 11:09:50.000,330
3,4,9.5,1384.000000,2023-01-03 12:55:38.361116,0.140000,0.233477,fused,34.696844,2023-01-03 12:55:38.000,6753
4,5,96.0,1803.099976,2023-01-03 14:30:50.201439,1.322572,0.633311,fused,35.048499,2023-01-03 14:30:48.000,5195

Done to check for categorical features

In [16]:
gps.nunique()

id                   85827
accuracy             14073
altitude             17916
created_at           85826
land_speed           10921
latitude             48203
location_provider        3
longitude            45931
time_of_fix          75254
user_id               8337
dtype: int64

In [8]:
gps.isna().sum()

id                   0
accuracy             0
altitude             0
created_at           0
land_speed           0
latitude             0
location_provider    0
longitude            0
time_of_fix          0
user_id              0
dtype: int64

In [5]:
gps.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85827 entries, 0 to 85826
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 85827 non-null  int64
 1   accuracy           85827 non-null  float64
 2   altitude           85827 non-null  float64
 3   created_at         85827 non-null  object
 4   land_speed         85827 non-null  float64
 5   latitude           85827 non-null  float64
 6   location_provider  85827 non-null  object
 7   longitude          85827 non-null  float64
 8   time_of_fix        85827 non-null  object
 9   user_id            85827 non-null  int64
dtypes: float64(5), int64(2), object(3)
memory usage: 6.5+ MB

In [6]:
gps.describe()

,id,accuracy,altitude,land_speed,latitude,longitude,user_id
count,85827.000000,8.582700e+04,85827.000000,85827.000000,85827.000000,85827.000000,85827.000000
mean,42914.000000,1.276606e+03,577.426159,0.118806,-1.005912,36.747582,4935.864623
std,24776.265114,1.310658e+04,812.168600,0.758115,2.380850,3.758306,2836.723821
min,1.000000,-2.147469e+06,-387.995000,-1.000000,-26.018018,-118.780216,1.000000
25%,21457.500000,1.888700e+01,0.000000,0.000000,-1.318829,35.252813,2633.000000
50%,42914.000000,4.000000e+02,0.000000,0.000000,-1.089409,36.824877,4632.000000
75%,64370.500000,2.000000e+03,1510.150000,0.000000,-0.093670,37.253718,7437.000000
max,85827.000000,2.000000e+06,10948.911088,79.085014,55.870016,138.359772,10111.000000

### Events

In [10]:
events.head()

,id,phone_instance_id,action,screen_name,timestamp,created_at,user_id,session_id,network_type
0,5541435,2869,action_1,screen_name_4,2021-10-07 17:06:19.000,2021-10-07 17:06:42.946302,6833,NaN,3G
1,5541436,2678,action_1,screen_name_4,2021-10-23 16:17:19.000,2021-10-23 16:19:08.208326,7275,NaN,3G
2,5541437,11545,action_1,screen_name_5,2021-10-19 08:10:12.000,2021-10-19 08:10:51.087983,4571,NaN,WiFi
3,5541438,5362,action_1,screen_name_5,2021-10-02 14:23:20.000,2021-10-02 14:23:53.730693,4912,NaN,WiFi
4,5541439,9029,action_1,screen_name_4,2021-10-31 10:16:07.000,2021-10-31 10:17:51.461670,7471,NaN,3G

In [11]:
events.isna().sum()

id                         0
phone_instance_id          0
action                     0
screen_name                0
timestamp                  0
created_at                 0
user_id                    0
session_id           3092843
network_type         1485473
dtype: int64

Done to check for categorical features

In [12]:
events.nunique()

id                   6296402
phone_instance_id      24030
action                    59
screen_name              516
timestamp            3329355
created_at           1549133
user_id                10111
session_id             85889
network_type               4
dtype: int64

In [13]:
events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6296402 entries, 0 to 6296401
Data columns (total 9 columns):
 #   Column             Dtype
---  ------             -----
 0   id                 int64
 1   phone_instance_id  int64
 2   action             object
 3   screen_name        object
 4   timestamp          object
 5   created_at         object
 6   user_id            int64
 7   session_id         object
 8   network_type       object
dtypes: int64(3), object(6)
memory usage: 432.3+ MB

In [14]:
events.describe()

                 id  phone_instance_id       user_id
count  6.296402e+06       6.296402e+06  6.296402e+06
mean   3.148202e+06       6.109728e+03  5.141554e+03
std    1.817615e+06       5.756800e+03  2.896312e+03
min    1.000000e+00       1.000000e+00  1.000000e+00
25%    1.574101e+06       1.581000e+03  2.654000e+03
50%    3.148202e+06       3.926000e+03  5.245000e+03
75%    4.722302e+06       9.399000e+03  7.650000e+03
max    6.296402e+06       2.403000e+04  1.011100e+04

### Loan Outcomes Train

In [15]:
outcomes.head()

   user_id              application_at  is_repaid
0     7140  2024-07-16 08:30:01.045957       True
1     3029  2023-03-19 16:48:46.899241      False
2     7310  2022-03-24 07:09:02.555562      False
3     7147  2022-04-04 03:55:34.998104      False
4      652  2023-07-09 15:46:29.127947      False